import{a as b,i as c,S as L}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const m="/goit-js-hw-12/assets/bi_x-octagon-ddf7add7.svg";let w="";async function p(){const i="https://pixabay.com/api/?key=42272856-fbb9ecaa9aa7f62044da3b204";try{const{data:a}=await b.get(i,{params:{image_type:"photo",orientation:"horizontal",safesearch:"true",q:w,per_page:PER_PAGE,page:currentPage}});return a}catch(a){console.error("Сталася помилка при отриманні зображень:",a.message)}}const s={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".btn-load-more")};let g="",u=1,y=0;const v=15;s.form.addEventListener("submit",P);s.btnLoadMore.addEventListener("click",C);async function P(e){if(e.preventDefault(),s.btnLoadMore.classList.add("hidden"),g===e.target.elements.query.value.trim()){e.target.reset(),d();return}else g=e.target.elements.query.value.trim();u=1,s.gallery.textContent="",n();try{const r=await p();if(g)parseInt(r.totalHits)>0?(d(),f(r.hits),y=r.totalHits,h(),n()):(c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:m,color:"white",timeout:2e3}),n());else{c.warning({message:"Sorry, you forgot to enter a search term. Please try again!",position:"topRight",messageSize:"16px",timeout:2e3}),n();return}}catch{c.error({message:"Error",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:m,color:"white",timeout:2e3}),n()}e.target.reset()}function S({largeImageURL:e,webformatURL:r,tags:i,likes:a,views:t,comments:o,downloads:l}){return`<a class='gallery-link' href='${e}'><img class='gallery-image' src='${r}' alt='${i}'/>
  <div class='gallery-review'>
  <div class='gallery-review-item'><b>Likes</b> <span>${a}</span></div>
  <div class='gallery-review-item'><b>Views</b> <span>${t}</span></div>
  <div class='gallery-review-item'><b>Comments</b> <span>${o}</span></div>
  <div class='gallery-review-item'><b>Downloads</b> <span>${l}</span></div>
  </div></a>
    `}let q=new L(".gallery a",{showCounter:!1,captionDelay:250,captions:!0,captionsData:"alt",captionPosition:"bottom"});function f(e){const r=e.map(S).join("");s.gallery.insertAdjacentHTML("beforeend",r),q.refresh()}async function C(){n(),d(),u+=1;const e=await p();f(e.hits),d(),h(),n(),E()}function h(){Math.ceil(y/v)<=u&&(s.btnLoadMore.classList.add("hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageSize:"16px",timeout:2e3}))}function n(){s.loader.classList.toggle("hidden")}function d(){s.btnLoadMore.classList.toggle("hidden")}function E(){const e=document.querySelector(".gallery-link");if(e){const i=e.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}else return}
//# sourceMappingURL=commonHelpers.js.map
