import{a as b,i as c,S as L}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const m="/goit-js-hw-12/assets/bi_x-octagon-ddf7add7.svg";async function p(){const s="https://pixabay.com/api/?key=42132229-e88b92984f0d2a7001cb07c65";try{const{data:a}=await b.get(s,{params:{image_type:"photo",orientation:"horizontal",safesearch:"true",q:w,per_page:P,page:v}});return a}catch(a){console.error("Сталася помилка при отриманні зображень:",a.message)}}let w="",v=1;const P=15;function S({largeImageURL:e,webformatURL:r,tags:s,likes:a,views:t,comments:o,downloads:l}){return`<a class='gallery-link' href='${e}'><img class='gallery-image' src='${r}' alt='${s}'/>
  <div class='gallery-review'>
  <div class='gallery-review-item'><b>Likes</b> <span>${a}</span></div>
  <div class='gallery-review-item'><b>Views</b> <span>${t}</span></div>
  <div class='gallery-review-item'><b>Comments</b> <span>${o}</span></div>
  <div class='gallery-review-item'><b>Downloads</b> <span>${l}</span></div>
  </div></a>
    `}let $=new SimpleLightbox(".gallery a",{showCounter:!1,captionDelay:250,captions:!0,captionsData:"alt",captionPosition:"bottom"});function y(e){const r=e.map(S).join("");refs.gallery.insertAdjacentHTML("beforeend",r),$.refresh()}const n={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".btn-load-more")};let g="",u=1,f=0;const C=15;n.form.addEventListener("submit",q);n.btnLoadMore.addEventListener("click",x);async function q(e){if(e.preventDefault(),n.btnLoadMore.classList.add("hidden"),g===e.target.elements.query.value.trim()){e.target.reset(),d();return}else g=e.target.elements.query.value.trim();u=1,n.gallery.textContent="",i();try{const r=await p();if(g)parseInt(r.totalHits)>0?(d(),y(r.hits),f=r.totalHits,h(),i()):(c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:m,color:"white",timeout:2e3}),i());else{c.warning({message:"Sorry, you forgot to enter a search term. Please try again!",position:"topRight",messageSize:"16px",timeout:2e3}),i();return}}catch{c.error({message:"Error",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:m,color:"white",timeout:2e3}),i()}e.target.reset()}new L(".gallery a",{showCounter:!1,captionDelay:250,captions:!0,captionsData:"alt",captionPosition:"bottom"});async function x(){i(),d(),u+=1;const e=await p();y(e.hits),d(),h(),i(),E()}function h(){Math.ceil(f/C)<=u&&(n.btnLoadMore.classList.add("hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageSize:"16px",timeout:2e3}))}function i(){n.loader.classList.toggle("hidden")}function d(){n.btnLoadMore.classList.toggle("hidden")}function E(){const e=document.querySelector(".gallery-link");if(e){const s=e.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}else return}
//# sourceMappingURL=commonHelpers.js.map
